### PR TITLE
Dependency Update

### PR DESCRIPTION
**Pull request by manuel-jrs**
JSON2 updated.

### CODE REVIEW

**Comment by FreeleX** [comment]
Hello, thank you for pull request. Could you tell what are the reasons behind updating JSON2 lib? And what benefits this change can bring to MLyrics? Thanks.

**Comment by manuel-jrs** [comment]
Yes, I'm working on a version with all the Lyrics updated sources (I almost finish). I thought this Project wasn't active because the last update was a lot time ago. So, this pull request was to see if you were still active. I tried to get you email in the forum, nightingale site and here, but I didn't success.

**Comment by FreeleX** [comment]
OK, looking forward to your changes. I believe you can write me PM on getnightingale.com

**Comment by FreeleX** [comment]
Closing this PR. You are welcome to propose any other PR.

**Pull request closed without merging**
